# Generated by Django 5.1 on 2024-08-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('1', 'Sphere'), ('2', 'box'), ('3', 'cylinder')], default='1', max_length=2),
        ),
    ]
